spring:
  application:
    name: movie-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}

datasource:
  jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/exampledb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
  vault-creds-path: database/creds/movie-role

app:
  vault-kv-secret-path: secret/movie-service

vault:
  uri: ${VAULT_URI:http://localhost:8200}
  app-role:
    role-id: movie-service-role-id

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.vault: DEBUG
